databases:
  - name: francis-academy-db
    databaseName: francis_academy
    user: francis_academy_user

services:
  - type: web
    name: francis-academy
    runtime: python3
    buildCommand: "./build.sh"
    startCommand: "gunicorn francis_academy.wsgi:application"
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: francis-academy-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
